export const tokens = {
  color: {
    studyGreen: "var(--color-study-green)",
    studyGreenBright: "var(--color-study-green-bright)",
    coolPaper: "var(--color-cool-paper)",
    coolPaperSecondary: "var(--color-cool-paper-secondary)",
    coolPaperTertiary: "var(--color-cool-paper-tertiary)",
    coolPaperElevated: "var(--color-cool-paper-elevated)",
    coolPaperGrouped: "var(--color-cool-paper-grouped)",
    surface: "var(--color-surface)",
    surfaceSecondary: "var(--color-surface-secondary)",
    ink: "var(--color-ink)",
    inkMuted: "var(--color-ink-muted)",
    inkFaint: "var(--color-ink-faint)",
    inkQuaternary: "var(--color-ink-quaternary)",
    label: "var(--color-label)",
    labelSecondary: "var(--color-label-secondary)",
    labelTertiary: "var(--color-label-tertiary)",
    labelQuaternary: "var(--color-label-quaternary)",
    separator: "var(--color-separator)",
    opaqueSeparator: "var(--color-opaque-separator)",
    destructive: "var(--color-destructive)",
    success: "var(--color-success)",
    warning: "var(--color-warning)",
    info: "var(--color-info)",
    chart: {
      emerald: "var(--color-chart-emerald)",
      green: "var(--color-chart-green)",
      amber: "var(--color-chart-amber)",
      blue: "var(--color-chart-blue)",
      red: "var(--color-chart-red)",
    },
  },
  typography: {
    family: {
      display:
        'var(--font-heading), Outfit, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "SF Pro", sans-serif',
      body: 'var(--font-sans), Geist, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "SF Pro", sans-serif',
      mono: 'var(--font-mono), "Geist Mono", "SF Mono", "SFMono-Regular", "Fira Code", monospace',
    },
    style: {
      largeTitle: "var(--fs-large-title)",
      title1: "var(--fs-title-1)",
      title2: "var(--fs-title-2)",
      title3: "var(--fs-title-3)",
      headline: "var(--fs-headline)",
      body: "var(--fs-body)",
      callout: "var(--fs-callout)",
      subhead: "var(--fs-subhead)",
      footnote: "var(--fs-footnote)",
      caption1: "var(--fs-caption-1)",
      caption2: "var(--fs-caption-2)",
    },
  },
  spacing: {
    "1": "var(--space-1)",
    "2": "var(--space-2)",
    "3": "var(--space-3)",
    "4": "var(--space-4)",
    "5": "var(--space-5)",
    "6": "var(--space-6)",
    "7": "var(--space-7)",
    "8": "var(--space-8)",
    "10": "var(--space-10)",
    "11": "var(--space-11)",
    "12": "var(--space-12)",
    "16": "var(--space-16)",
    "20": "var(--space-20)",
    "24": "var(--space-24)",
    "32": "var(--space-32)",
    "40": "var(--space-40)",
    "44": "var(--space-44)",
  },
  touch: {
    min: "var(--touch-min)",
    default: "var(--touch-default)",
    padding: "var(--touch-padding)",
    paddingNoBezel: "var(--touch-padding-no-bezel)",
  },
  radius: {
    none: "0",
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    "2xl": "var(--radius-2xl)",
    "3xl": "var(--radius-3xl)",
    "4xl": "var(--radius-4xl)",
    full: "9999px",
  },
  shadow: {
    none: "none",
    level1: "var(--shadow-level-1)",
    level2: "var(--shadow-level-2)",
    level3: "var(--shadow-level-3)",
    solverGlow: "var(--shadow-solver)",
  },
  motion: {
    duration: {
      instant: "var(--motion-duration-instant)",
      fast: "var(--motion-duration-fast)",
      normal: "var(--motion-duration-normal)",
      slow: "var(--motion-duration-slow)",
      slower: "var(--motion-duration-slower)",
      max: "var(--motion-duration-max)",
    },
    easing: {
      default: "var(--motion-easing-default)",
      overshoot: "var(--motion-easing-overshoot)",
      decelerate: "var(--motion-easing-decelerate)",
      accelerate: "var(--motion-easing-accelerate)",
    },
  },
  zIndex: {
    content: "var(--z-content)",
    elevated: "var(--z-elevated)",
    sticky: "var(--z-sticky)",
    header: "var(--z-header)",
    drawer: "var(--z-drawer)",
    cookieBanner: "var(--z-cookie-banner)",
    modal: "var(--z-modal)",
    overlay: "var(--z-overlay)",
    toast: "var(--z-toast)",
    skipLink: "var(--z-skip-link)",
    easterEgg: "var(--z-easter-egg)",
    pdfControls: "var(--z-pdf-controls)",
    contextual: "var(--z-contextual)",
  },
  glass: {
    ultraThin: { blur: "var(--glass-ultra-thin)" },
    thin: { blur: "var(--glass-thin)" },
    regular: { blur: "var(--glass-regular)" },
    thick: { blur: "var(--glass-thick)" },
    card: { blur: "var(--glass-card)" },
    cardStrong: { blur: "var(--glass-card-strong)" },
  },
} as const;
