export const APPWRITE_DATABASE_ID = process.env.APPWRITE_DATABASE_ID ?? "";

export const COLLECTIONS = {
  SUBJECTS: "subjects",
  TOPICS: "topics",
  QUESTIONS: "questions",
  USER_SUBJECTS: "user_subjects",
  USER_PROGRESS: "user_progress",
  STUDY_SESSIONS: "study_sessions",
  EXAM_PAPERS: "exam_papers",
  VISUALS: "visuals",
  COMPETENCIES: "competencies",
  EXAM_SESSIONS: "exam_sessions",
  REFERRAL_CODES: "referral_codes",
  REFERRALS: "referrals",
  STUDY_PLANS: "study_plans",
  QUESTION_FLAGS: "question_flags",
  ANALYTICS: "analytics",
  FLASHCARDS: "flashcards",
  WRONG_ANSWERS: "wrong_answers",
  CHAT_MESSAGES: "chat_messages",
  EXAM_DATES: "exam_dates",
  TEACHER_STUDENTS: "teacher_students",
  TEACHER_ASSIGNMENTS: "teacher_assignments",
  PARENT_STUDENTS: "parent_students",
  FLASHCARD_REVIEWS: "flashcard_reviews",
  STUDY_GROUPS: "study_groups",
  GROUP_MEMBERS: "group_members",
  GROUP_INVITES: "group_invites",
  BOOKMARKS: "bookmarks",
  NOTES: "notes",
  GROUP_POSTS: "group_posts",
  USER_GAMIFICATION: "user_gamification",
  GROUP_COMMENTS: "group_comments",
  GROUP_REACTIONS: "group_reactions",
  PAST_PAPER_QUESTIONS: "past_paper_questions",
  GROUP_CHALLENGES: "group_challenges",
  GROUP_CHALLENGE_ENTRIES: "group_challenge_entries",
  GROUP_BADGES: "group_badges",
  USER_CONSENTS: "user_consents",
  ASSIGNMENT_SUBMISSIONS: "assignment_submissions",
  SHARED_QUESTIONS: "shared_questions",
  TEACHER_OBSERVATIONS: "teacher_observations",
  ASSIGNMENT_MESSAGES: "assignment_messages",
  GHOST_LINKS: "ghost_links",
  LIVE_SESSIONS: "live_sessions",
} as const;
