// Auto-generated by scripts/generate-lottie-assets.mjs
// Do not edit manually — run `bun run scripts/generate-lottie-assets.mjs` to regenerate.

export const ANIMATION_SOURCES = {
	"achievement-unlock": "/animations/achievement-unlock.lottie",
	confetti: "/animations/confetti.lottie",
	"empty-search": "/animations/empty-search.lottie",
	"empty-upload": "/animations/empty-upload.lottie",
	"error-state": "/animations/error-state.lottie",
	"level-up": "/animations/level-up.lottie",
	"loading-dots": "/animations/loading-dots.lottie",
	"loading-lumni": "/animations/loading-lumni.lottie",
	"page-404": "/animations/page-404.lottie",
	"quiz-correct": "/animations/quiz-correct.lottie",
	"quiz-incorrect": "/animations/quiz-incorrect.lottie",
	"streak-fire": "/animations/streak-fire.lottie",
	"success-check": "/animations/success-check.lottie",
	"typing-indicator": "/animations/typing-indicator.lottie",
	"xp-burst": "/animations/xp-burst.lottie",
} as const;

export type AnimationSourceName = keyof typeof ANIMATION_SOURCES;
