export const TOAST_DURATION = 4000;
export const CELEBRATION_DURATION = 4000;
export const CLIPBOARD_CONFIRMATION_DURATION = 2000;
export const SAVED_INDICATOR_DURATION = 1500;
export const SUCCESS_BANNER_DURATION = 2000;
export const EGG_DISMISS_DURATION = 4000;
export const UPLOAD_CLOSE_DELAY = 1500;
export const SCHEDULER_DELAY = 1500;
