import type { Achievement, StreakMilestone, RewardChestDef } from "./gamification-types";

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: "first_question",
    name: "First Steps",
    description: "Answer your first question",
    icon: "🎯",
    earnedAt: null,
    xpReward: 25,
    rarity: "common",
    category: "volume",
    requirement: 1,
  },
  {
    id: "streak_3",
    name: "On Fire",
    description: "Maintain a 3-day streak",
    icon: "🔥",
    earnedAt: null,
    xpReward: 50,
    rarity: "common",
    category: "streak",
    requirement: 3,
  },
  {
    id: "streak_7",
    name: "Week Warrior",
    description: "Maintain a 7-day streak",
    icon: "💪",
    earnedAt: null,
    xpReward: 100,
    rarity: "rare",
    category: "streak",
    requirement: 7,
  },
  {
    id: "streak_30",
    name: "Unstoppable",
    description: "Maintain a 30-day streak",
    icon: "🏆",
    earnedAt: null,
    xpReward: 500,
    rarity: "epic",
    category: "streak",
    requirement: 30,
  },
  {
    id: "questions_50",
    name: "Dedicated",
    description: "Answer 50 questions",
    icon: "📚",
    earnedAt: null,
    xpReward: 75,
    rarity: "common",
    category: "volume",
    requirement: 50,
  },
  {
    id: "questions_100",
    name: "Scholar",
    description: "Answer 100 questions",
    icon: "🎓",
    earnedAt: null,
    xpReward: 150,
    rarity: "rare",
    category: "volume",
    requirement: 100,
  },
  {
    id: "questions_500",
    name: "Expert",
    description: "Answer 500 questions",
    icon: "⭐",
    earnedAt: null,
    xpReward: 300,
    rarity: "epic",
    category: "volume",
    requirement: 500,
  },
  {
    id: "accuracy_80",
    name: "Sharp Mind",
    description: "Achieve 80% accuracy",
    icon: "🧠",
    earnedAt: null,
    xpReward: 100,
    rarity: "rare",
    category: "accuracy",
    requirement: 80,
  },
  {
    id: "accuracy_90",
    name: "Perfectionist",
    description: "Achieve 90% accuracy",
    icon: "💎",
    earnedAt: null,
    xpReward: 200,
    rarity: "epic",
    category: "accuracy",
    requirement: 90,
  },
  {
    id: "perfect_quiz",
    name: "Flawless",
    description: "Complete a quiz with 100% accuracy",
    icon: "✨",
    earnedAt: null,
    xpReward: 150,
    rarity: "rare",
    category: "special",
    requirement: 1,
  },
  {
    id: "level_5",
    name: "Rising Star",
    description: "Reach level 5",
    icon: "🌟",
    earnedAt: null,
    xpReward: 200,
    rarity: "rare",
    category: "special",
    requirement: 5,
  },
  {
    id: "level_10",
    name: "Mastery",
    description: "Reach level 10",
    icon: "👑",
    earnedAt: null,
    xpReward: 500,
    rarity: "legendary",
    category: "special",
    requirement: 10,
  },
  {
    id: "subject_math_50",
    name: "Math Whiz",
    description: "Answer 50 math questions",
    icon: "🔢",
    earnedAt: null,
    xpReward: 75,
    rarity: "common",
    category: "subject",
    requirement: 50,
  },
  {
    id: "subject_math_200",
    name: "Math Master",
    description: "Answer 200 math questions",
    icon: "🎲",
    earnedAt: null,
    xpReward: 200,
    rarity: "epic",
    category: "subject",
    requirement: 200,
  },
  {
    id: "subject_science_50",
    name: "Science Star",
    description: "Answer 50 science questions",
    icon: "🔬",
    earnedAt: null,
    xpReward: 75,
    rarity: "common",
    category: "subject",
    requirement: 50,
  },
  {
    id: "subject_science_200",
    name: "Science Sage",
    description: "Answer 200 science questions",
    icon: "🧪",
    earnedAt: null,
    xpReward: 200,
    rarity: "epic",
    category: "subject",
    requirement: 200,
  },
  {
    id: "subject_language_50",
    name: "Wordsmith",
    description: "Answer 50 language questions",
    icon: "📖",
    earnedAt: null,
    xpReward: 75,
    rarity: "common",
    category: "subject",
    requirement: 50,
  },
  {
    id: "subject_language_200",
    name: "Linguist",
    description: "Answer 200 language questions",
    icon: "🗣️",
    earnedAt: null,
    xpReward: 200,
    rarity: "epic",
    category: "subject",
    requirement: 200,
  },
  {
    id: "subject_commerce_50",
    name: "Trader",
    description: "Answer 50 commerce questions",
    icon: "💼",
    earnedAt: null,
    xpReward: 75,
    rarity: "common",
    category: "subject",
    requirement: 50,
  },
  {
    id: "subject_commerce_200",
    name: "Tycoon",
    description: "Answer 200 commerce questions",
    icon: "📊",
    earnedAt: null,
    xpReward: 200,
    rarity: "epic",
    category: "subject",
    requirement: 200,
  },
  {
    id: "subjects_all_5",
    name: "Polyglot",
    description: "Answer questions in 5 different subjects",
    icon: "🌍",
    earnedAt: null,
    xpReward: 150,
    rarity: "rare",
    category: "subject",
    requirement: 5,
  },
  {
    id: "mistake_review_master",
    name: "Review Master",
    description: "Review 20 past mistakes",
    icon: "🔄",
    earnedAt: null,
    xpReward: 100,
    rarity: "common",
    category: "special",
    requirement: 20,
  },
  {
    id: "flashcard_focused_50",
    name: "Focused Learner",
    description: "Answer 50 consecutive flashcards correctly",
    icon: "⚡",
    earnedAt: null,
    xpReward: 200,
    rarity: "epic",
    category: "special",
    requirement: 50,
  },
  {
    id: "competency_climber",
    name: "Competency Climber",
    description: "Reach Proficient in 5 topics",
    icon: "📈",
    earnedAt: null,
    xpReward: 150,
    rarity: "rare",
    category: "special",
    requirement: 5,
  },
  {
    id: "weakness_slayer",
    name: "Weakness Slayer",
    description: "Improve a topic score by 20%",
    icon: "💪",
    earnedAt: null,
    xpReward: 150,
    rarity: "rare",
    category: "special",
    requirement: 20,
  },
  {
    id: "study_plan_streak_7",
    name: "Plan Follower",
    description: "Complete 7 consecutive study plan days",
    icon: "📅",
    earnedAt: null,
    xpReward: 120,
    rarity: "rare",
    category: "special",
    requirement: 7,
  },
  {
    id: "exam_comeback",
    name: "Exam Comeback",
    description: "Improve your exam score by 15% from your previous attempt",
    icon: "🎯",
    earnedAt: null,
    xpReward: 200,
    rarity: "epic",
    category: "special",
    requirement: 15,
  },
  {
    id: "leaderboard_top_50",
    name: "Rising Competitor",
    description: "Reach the top 50 on the weekly leaderboard",
    icon: "📊",
    earnedAt: null,
    xpReward: 100,
    rarity: "rare",
    category: "special",
    requirement: 50,
  },
  {
    id: "leaderboard_top_10",
    name: "Elite Performer",
    description: "Reach the top 10 on the weekly leaderboard",
    icon: "🏅",
    earnedAt: null,
    xpReward: 300,
    rarity: "epic",
    category: "special",
    requirement: 10,
  },
  {
    id: "leaderboard_subject_top_10",
    name: "Subject Champion",
    description: "Reach the top 10 in any subject leaderboard",
    icon: "🎯",
    earnedAt: null,
    xpReward: 200,
    rarity: "rare",
    category: "special",
    requirement: 10,
  },
];

export const STREAK_MILESTONES: StreakMilestone[] = [
  { streak: 3, reward: "First badge earned!", unlocked: false },
  { streak: 7, reward: "Week Warrior badge unlocked!", unlocked: false },
  { streak: 14, reward: "2x XP boost for a day!", unlocked: false },
  { streak: 30, reward: "Unstoppable badge + 200 XP!", unlocked: false },
  { streak: 60, reward: "Legendary aura effect!", unlocked: false },
  { streak: 100, reward: "Grandmaster title unlocked!", unlocked: false },
];

export const REWARD_CHESTS: RewardChestDef[] = [
  {
    id: "chest_500",
    name: "Wooden Chest",
    description: "Reach 500 total XP",
    xpRequired: 500,
    xpReward: 50,
    icon: "🪵",
    rarity: "common",
  },
  {
    id: "chest_1000",
    name: "Bronze Chest",
    description: "Reach 1,000 total XP",
    xpRequired: 1000,
    xpReward: 100,
    icon: "🥉",
    rarity: "common",
  },
  {
    id: "chest_2500",
    name: "Silver Chest",
    description: "Reach 2,500 total XP",
    xpRequired: 2500,
    xpReward: 200,
    icon: "🥈",
    rarity: "rare",
  },
  {
    id: "chest_5000",
    name: "Golden Chest",
    description: "Reach 5,000 total XP",
    xpRequired: 5000,
    xpReward: 400,
    icon: "🥇",
    rarity: "rare",
  },
  {
    id: "chest_10000",
    name: "Crystal Chest",
    description: "Reach 10,000 total XP",
    xpRequired: 10000,
    xpReward: 800,
    icon: "💎",
    rarity: "epic",
  },
  {
    id: "chest_25000",
    name: "Obsidian Chest",
    description: "Reach 25,000 total XP",
    xpRequired: 25000,
    xpReward: 1500,
    icon: "🪨",
    rarity: "legendary",
  },
];
